In [5]:
'''
Format
This data frame contains the following columns:

crim
per capita crime rate by town.

zn
proportion of residential land zoned for lots over 25,000 sq.ft.

indus
proportion of non-retail business acres per town.

chas
Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).

nox
nitrogen oxides concentration (parts per 10 million).

rm
average number of rooms per dwelling.

age
proportion of owner-occupied units built prior to 1940.

dis
weighted mean of distances to five Boston employment centres.

rad
index of accessibility to radial highways.

tax
full-value property-tax rate per \$10,000.

ptratio
pupil-teacher ratio by town.

black
1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town.

lstat
lower status of the population (percent).

medv
median value of owner-occupied homes in \$1000s.
'''

'\nFormat\nThis data frame contains the following columns:\n\ncrim\nper capita crime rate by town.\n\nzn\nproportion of residential land zoned for lots over 25,000 sq.ft.\n\nindus\nproportion of non-retail business acres per town.\n\nchas\nCharles River dummy variable (= 1 if tract bounds river; 0 otherwise).\n\nnox\nnitrogen oxides concentration (parts per 10 million).\n\nrm\naverage number of rooms per dwelling.\n\nage\nproportion of owner-occupied units built prior to 1940.\n\ndis\nweighted mean of distances to five Boston employment centres.\n\nrad\nindex of accessibility to radial highways.\n\ntax\nfull-value property-tax rate per \\$10,000.\n\nptratio\npupil-teacher ratio by town.\n\nblack\n1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town.\n\nlstat\nlower status of the population (percent).\n\nmedv\nmedian value of owner-occupied homes in \\$1000s.\n'

In [2]:
import pandas as pd
Boston = pd.read_csv("/home/labsuser/Datasets/boston.csv")

In [6]:
Boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
# step 1 - correlation analysis
Correlation_Boston = Boston.corr()
Correlation_Boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
crim,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
zn,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
indus,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
chas,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
nox,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
rm,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
age,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
dis,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
rad,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
tax,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
ptratio,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
black,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
lstat,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
medv,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

In [ ]:
# simple linear regression

In [13]:
# step 2 - splitting x and y variables
import pandas as pd
x=pd.DataFrame(Boston['rm'])
y=Boston['medv']

In [14]:
# Step 3 - Running model
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
Model_Boston = lm.fit(x,y) 
#or
Model_Boston = LinearRegression().fit(x,y)

In [15]:
print(Model_Boston.intercept_)
print(Model_Boston.coef_)

-34.67062077643857
[9.10210898]

In [17]:
# Step 4 -  Making predictions 
pred_medv = Model_Boston.predict(x)
len(pred_medv)

506

In [21]:
Boston_predicted = pd.concat([Boston,pd.DataFrame(pred_medv,columns=['Predicted_price'])],axis=1)
Boston_predicted

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv,Predicted_price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,25.175746
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,23.774021
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,30.728032
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,29.025938
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,30.382152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4,25.339584
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6,21.034286
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9,28.825691
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0,27.169108
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9,20.215096

In [22]:
Boston_predicted['Error_pct'] = abs(Boston_predicted.medv-Boston_predicted.Predicted_price)/Boston_predicted.medv

In [23]:
Boston_predicted

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv,Predicted_price,Error_pct
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,25.175746,0.048989
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,23.774021,0.100649
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,30.728032,0.114466
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,29.025938,0.130960
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,30.382152,0.160714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4,25.339584,0.131231
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6,21.034286,0.021082
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9,28.825691,0.206096
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0,27.169108,0.234959
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9,20.215096,0.698748

In [24]:
Boston_predicted['Error_pct'].mean()

0.2576730037686979

In [25]:
# accuracy rate
1- Boston_predicted['Error_pct'].mean()

0.7423269962313022

In [ ]:
######################## Simple linear regression with Train and Test data split ########################
# step 2 - splitting x and y variables
import pandas as pd
x=pd.DataFrame(Boston['rm'])
y=Boston['medv']

In [26]:
# Step 2-  Important. Sampling. NOTE – function “train_test_split” 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =  train_test_split(x,y,test_size=.33)

In [27]:
print(x_test.shape)
print(y_test.shape)
print(x_train.shape)
print(y_train.shape)

(167, 1)
(167,)
(339, 1)
(339,)

In [28]:
# Step 3 - Running model in Training data
from sklearn.linear_model import LinearRegression
Model_Boston = LinearRegression().fit(x_train,y_train)

In [29]:
print(Model_Boston.intercept_)
print(Model_Boston.coef_)

-33.277405306374845
[8.89298478]

In [31]:
# Step 4 -  Making predictions 
pred_medv = Model_Boston.predict(x_test)
len(pred_medv)

167

In [39]:
Final_test_data = pd.concat([pd.concat([x_test,y_test],axis=1).reset_index(),pd.DataFrame(pred_medv,columns=['predicted'])],axis=1)
Final_test_data

     index     rm  medv  predicted
0      496  5.390  19.7  14.655783
1       27  6.047  14.8  20.498474
2      273  7.691  35.2  35.118541
3       81  6.619  23.9  25.585261
4       35  5.933  18.9  19.484673
..     ...    ...   ...        ...
162    295  6.678  28.6  26.109947
163    274  6.758  32.4  26.821386
164    412  4.628  17.9   7.879328
165    447  6.251  12.6  22.312643
166    210  5.960  21.7  19.724784

[167 rows x 4 columns]

In [40]:
Final_test_data['Error_pct'] = abs(Final_test_data.medv-Final_test_data.predicted)/Final_test_data.medv

In [42]:
Final_test_data.Error_pct.mean()

0.2638060212325639

In [43]:
1-Final_test_data.Error_pct.mean()

0.7361939787674361

In [46]:
######################## multiple linear regression –  ########################
import pandas as pd
x=Boston.drop('medv',axis=1)
y=Boston['medv']

from sklearn.linear_model import LinearRegression 
lm = LinearRegression()
boson_equation = lm.fit(x,y) 
# equation beta coefficients
print(boson_equation.intercept_)
print(x.columns)
print(boson_equation.coef_)

36.45948838509004
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat'],
      dtype='object')
[-1.08011358e-01  4.64204584e-02  2.05586264e-02  2.68673382e+00
 -1.77666112e+01  3.80986521e+00  6.92224640e-04 -1.47556685e+00
  3.06049479e-01 -1.23345939e-02 -9.52747232e-01  9.31168327e-03
 -5.24758378e-01]

In [50]:
boson_equation.score(x,y)

0.7406426641094094

In [47]:
## making predictions
Predicted_values = boson_equation.predict(x)
Predicted_values
Predicted_values = pd.DataFrame(Predicted_values,columns=['Predicted Price of house'])

In [48]:
## adding predicted values to original data
Predicted_Price_table = pd.concat([x,y,Predicted_values],axis=1)
Predicted_Price_table

### finding out error percentages
Predicted_Price_table['Residual'] = abs(Predicted_Price_table.medv - Predicted_Price_table['Predicted Price of house'])/Predicted_Price_table.medv
Predicted_Price_table
1-Predicted_Price_table.Residual.mean()

0.8358270119351002